### ISSUE TITLE
After initial docker-compose setup server container keeps restarting: ConfigException$UnresolvedSubstitution

### ISSUE THREAD

**Issue by retmarut** [OpenOlitor/openolitor-docker-compose#8]
Following the instructions from this repo the stack comes up almost alright, besides de server container...

> $ docker-compose ps
> `                     Name                                    Command                  State                                             Ports                                       
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> openolitor-docker-compose_client-admin_1          /docker-entrypoint.sh ngin ...   Up             80/tcp                                                                            
> openolitor-docker-compose_client-kundenportal_1   /docker-entrypoint.sh ngin ...   Up             80/tcp                                                                            
> openolitor-docker-compose_db_1                    docker-entrypoint.sh mariadbd    Up             0.0.0.0:3306->3306/tcp,:::3306->3306/tcp                                          
> openolitor-docker-compose_nginx_1                 /docker-entrypoint.sh ngin ...   Up             80/tcp, 0.0.0.0:8080->9000/tcp,:::8080->9000/tcp                                  
> openolitor-docker-compose_pdf-tool_1              /docker-entrypoint.sh --sp ...   Up             0.0.0.0:9040->8080/tcp,:::9040->8080/tcp                                          
> openolitor-docker-compose_s3_1                    /usr/bin/docker-entrypoint ...   Up (healthy)   0.0.0.0:9050->9000/tcp,:::9050->9000/tcp                                          
> openolitor-docker-compose_server_1                /opt/docker/bin/openolitor ...   **Restarting**                                                                                       
> openolitor-docker-compose_smtp-proxy_1            MailHog                          Up             0.0.0.0:1025->1025/tcp,:::1025->1025/tcp, 0.0.0.0:8025->8025/tcp,:::8025->8025/tcp
 
With 
> $ docker-compose logs  server
I find the following recurring exception message:

> server_1               | Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: /etc/openolitor-server/application.conf: 5: Could not resolve substitution to a value: ${spray.version}                                                                                                                                                                           
> server_1               |        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
> server_1               |        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:183)
> server_1               |        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)
> server_1               |        at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
> server_1               |        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:183)
> server_1               |        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)

**Comment by AlwinEgger** [comment]
This is a mistake of course. It has to do with the latest update of the server component.

We will fix this and keep you posted...

**Comment by AlwinEgger** [comment]
This project has been updated to comply with the requirements of the 2.6.x version. So please try again and let us know if everything works.

**Comment by retmarut** [comment]
I wiped out the cloned repo and cloned it again.
After
docker-compose up -d db s3
and 
docker-compose up -d
the issue is not gone. Maybe I should have reset the docker-compose stack in a different way to make the fix work?

**Comment by AlwinEgger** [comment]
you have to pull the latest container again:

`docker-compose pull`

**Comment by retmarut** [comment]
After clearing the cloned git repo, cloning it from scratch, pulling images as you suggest, I saw s3 and the server images getting updated.
After starting s3 and after that the rest the issue remains:

~/openolitor-docker-compose$ docker-compose ps
                     Name                                    Command                  State                           Ports                     
------------------------------------------------------------------------------------------------------------------------------------------------
openolitor-docker-compose_client-admin_1          /docker-entrypoint.sh ngin ...   Up             80/tcp                                        
openolitor-docker-compose_client-kundenportal_1   /docker-entrypoint.sh ngin ...   Up             80/tcp                                        
openolitor-docker-compose_db_1                    docker-entrypoint.sh mariadbd    Up             0.0.0.0:3306->3306/tcp,:::3306->3306/tcp      
openolitor-docker-compose_nginx_1                 /docker-entrypoint.sh ngin ...   Up             80/tcp,                                       
                                                                                                  0.0.0.0:8080->9000/tcp,:::8080->9000/tcp      
openolitor-docker-compose_pdf-tool_1              /docker-entrypoint.sh --sp ...   Up             0.0.0.0:9040->8080/tcp,:::9040->8080/tcp      
openolitor-docker-compose_s3_1                    /usr/bin/docker-entrypoint ...   Up (healthy)   0.0.0.0:9050->9000/tcp,:::9050->9000/tcp      
openolitor-docker-compose_server_1                /opt/docker/bin/openolitor ...   Restarting                                                   
openolitor-docker-compose_smtp-proxy_1            MailHog                          Up             0.0.0.0:1025->1025/tcp,:::1025->1025/tcp,     
                                                                                                  0.0.0.0:8025->8025/tcp,:::8025->8025/tcp      


server_1               | 16:12:56,731 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
server_1               | 16:12:56,731 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
server_1               | 16:12:56,731 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@247bddad - Registering current configuration as safe fallback point
server_1               | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
server_1               | Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: /etc/openolitor-server/application.conf: 5: Could not resolve substitution to a value: ${spray.version}
server_1               | 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
server_1               | 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:183)
server_1               | 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:146)


~/openolitor-docker-compose$ docker images
REPOSITORY                                  TAG         IMAGE ID       CREATED        SIZE
openolitor/openolitor-server                latest      77a8e1095b2e   7 hours ago    506MB
minio/minio                                 latest      c1244bccda28   3 days ago     230MB
openolitor/openolitor-server                <none>      f004ebe9a3c0   9 days ago     506MB
minio/minio                                 <none>      1214e3c023d8   9 days ago     230MB
mariadb                                     10.7        3cad01fec9da   13 days ago    415MB
nginx                                       latest      51086ed63d8c   2 weeks ago    142MB
openolitor/openolitor-client-admin          latest      72a5b6bc919b   4 weeks ago    147MB
openolitor/openolitor-client-kundenportal   latest      8fc01aa97eb9   8 weeks ago    145MB
eugenmayer/jodconverter                     rest        ac189a26aed7   9 months ago   1.29GB
mailhog/mailhog                             latest      4de68494cd0d   2 years ago    392MB
requarks/wiki                               2           e39c938d01db   2 years ago    351MB
postgres                                    11-alpine   98efe01f6671   2 years ago    155MB

**Comment by AlwinEgger** [comment]
There was an issue with the latest minio version (not sure if you were affected) and the generate-script had a flaw. Do you generate the config-files?

So @retmarut it would be best to retry with the updated files from the repo.

If this is not working, we can also help you on a videocall session. This is usually the fastest.

**Comment by AlwinEgger** [comment]
Closed because of inactivity. @retmarut Please feel free to reopen in case your problems persist and you need additional help.
